summary(AirPassengers)
plot(AirPassengers)
par(mar=c(1,1,1,1))
abline(reg=lm(AirPassengers~time(AirPassengers)))
cycle(AirPassengers)
plot(aggregate(AirPassengers,FUN=mean))
boxplot(AirPassengers~cycle(AirPassengers))
adf.test(diff(log(AirPassengers)), alternative="stationary", k=0)
data: diff(log(AirPassengers))
adf.test(diff(log(AirPassengers)), alternative="stationary", k=0)
adf.test(diff(log(AirPassengers)), alternative="stationary", k=0)
log(AirPassengers)
adf.test(diff(log(AirPassengers)), alternative="stationary", k=0)
install.packages('tseries')
adf.test(diff(log(AirPassengers)), alternative="stationary", k=0)
adf.test(diff(log(AirPassengers)), alternative="stationary", k=0)
?adf.test
adf.test(diff(log(AirPassengers)), alternative="stationary", k=0)
log(AirPassengers)
adf.test(diff(diff(log(AirPassengers)), alternative="stationary", k=0))
pacf(diff(log(AirPassengers)))         
(fit <- arima(log(AirPassengers), c(0, 1, 1),seasonal = list(order = c(0, 1, 1), period = 12)))
pred <- predict(fit, n.ahead = 10*12)
ts.plot(AirPassengers,2.718^pred$pred, log = "y", lty = c(1,3))
plot(scale)
ts.plot(AirPassengers,2.718^pred$pred, log = "y", lty = c(1,3))
pred
pred1<- 2.718^pred
pred1
